### ISSUE TITLE
Error during /***/***/my-project/libs/shared/ui/package.json read

### ISSUE THREAD

**Issue by jogelin** [twittwer/nx-tools#59] opened 2022-02-02 10:35 UTC
It seems that the library is trying to read my `package.json` but it is trying to read it at my library root location instead of my project root location:

```
[11:16:35] Error during /***/***/my-project/libs/shared/ui/package.json read

[11:16:35] Continuing without package.json file
```

Any idea why?

This is my config:
```
"compodoc": {
      "executor": "@twittwer/compodoc:compodoc",
      "outputs": ["{options.outputPath}"],
      "options": {
        "tsConfig": "libs/shared/ui/tsconfig.lib.json",
        "outputPath": "dist/compodoc/shared-ui",
        "exportFormat": "json"
      },
      "configurations": {
        "watch": {
          "watch": true
        }
      }
    }
```

**Comment by twittwer** [comment] 2022-02-02 18:36
Duplicate of https://github.com/compodoc/compodoc/issues/1174

**Closed** 2022-02-02 18:44 UTC
